"""Add performance indexes for year, created_at, section, difficulty, topic, score, and completed_at

Revision ID: aa8f83c5dd2e
Revises: e7e5775393e6
Create Date: 2025-08-17 21:47:16.404153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8f83c5dd2e'
down_revision = 'e7e5775393e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic'), ['topic'], unique=False)

    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_attempts_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_attempts_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_attempts_started_at'), ['started_at'], unique=False)

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_year'))
        batch_op.drop_index(batch_op.f('ix_tests_created_at'))

    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_attempts_started_at'))
        batch_op.drop_index(batch_op.f('ix_test_attempts_score'))
        batch_op.drop_index(batch_op.f('ix_test_attempts_completed_at'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic'))
        batch_op.drop_index(batch_op.f('ix_questions_section'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty'))

    # ### end Alembic commands ###
